name: TodoHub
options:
  bundleIdPrefix: com.martinwoodward
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

packages:
  AppAuth:
    url: https://github.com/openid/AppAuth-iOS.git
    from: "1.7.0"

targets:
  TodoHub:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    supportedDestinations: [iOS, iPad]
    sources:
      - path: TodoHub
        excludes:
          - "**/*.md"
    settings:
      base:
        INFOPLIST_FILE: TodoHub/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.martinwoodward.todohub
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: AppAuth
    
  TodoHubTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TodoHubTests
    dependencies:
      - target: TodoHub
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.martinwoodward.todohub.tests
        GENERATE_INFOPLIST_FILE: YES

  TodoHubUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - TodoHubUITests
    dependencies:
      - target: TodoHub
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.martinwoodward.todohub.uitests
        GENERATE_INFOPLIST_FILE: YES

schemes:
  TodoHub:
    build:
      targets:
        TodoHub: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TodoHubTests
        - TodoHubUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
